apiVersion: apps/v1
kind: Deployment
initContainers:
  - name: download-helm
    image: alpine:3.20
    command: ["sh", "-c"]
    args:
      - |
        set -e
        apk add --no-cache curl
        curl -fsSL -o /custom-bin/helm.tar.gz \
          https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz
        tar -zxvf /custom-bin/helm.tar.gz -C /custom-bin
        mv /custom-bin/linux-amd64/helm /custom-bin/helm
        chmod +x /custom-bin/helm
    volumeMounts:
      - name: custom-helm-bin
        mountPath: /custom-bin

containers:
  - name: argocd-repo-server
    volumeMounts:
      - name: custom-helm-bin
        mountPath: /usr/local/bin/helm
        subPath: helm
  - name: argocd-server
    volumeMounts:
      - name: custom-helm-bin
        mountPath: /usr/local/bin/helm
        subPath: helm
  - name: argocd-applicationset-controller
    volumeMounts:
      - name: custom-helm-bin
        mountPath: /usr/local/bin/helm
        subPath: helm
  - name: argocd-notifications-controller
    volumeMounts:
      - name: custom-helm-bin
        mountPath: /usr/local/bin/helm
        subPath: helm

volumes:
  - name: custom-helm-bin
    emptyDir: {}